CREATE TABLE PROJECT_OWNER.MASURATORI (ID_MASURATOARE NUMBER NOT NULL,
NR_CICLU NUMBER NOT NULL,
CURENT_INCARCARE NUMBER,
TENSIUNE_INCARCARE NUMBER,
CURENT_DESCARCARE NUMBER,
TENSIUNE_DESCARCARE NUMBER,
CURENT_PRAG NUMBER NOT NULL,
TENSIUNE_PRAG NUMBER NOT NULL,
NUMAR_TOTAL_CICLURI NUMBER NOT NULL);

ALTER TABLE PROJECT_OWNER.MASURATORI ADD CONSTRAINT PK_MASURATORI PRIMARY KEY (ID_MASURATOARE);

CREATE SEQUENCE masuratori_id_seq START WITH 10000 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER masuratori_insert_trigger
BEFORE INSERT ON PROJECT_OWNER.MASURATORI
FOR EACH ROW
BEGIN
  SELECT masuratori_id_seq.NEXTVAL INTO :new.ID_MASURATOARE FROM dual;
END;

CREATE SEQUENCE ciclu_id_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE PROJECT_OWNER.CICLURI_INC_DESC
( 
ID_CICLU,
NR_CICLU,
CURENT_PRAG,
TENSIUNE_PRAG,
NUMAR_TOTAL_CICLURI,
ID_MASURATOARE
) AS SELECT ciclu_id_seq.NEXTVAL,
NR_CICLU,
CURENT_PRAG,
TENSIUNE_PRAG,
NUMAR_TOTAL_CICLURI,
ID_MASURATOARE FROM PROJECT_OWNER.MASURATORI WHERE 1=2;

ALTER TABLE PROJECT_OWNER.CICLURI_INC_DESC ADD CONSTRAINT PK_CICLURI PRIMARY KEY (ID_CICLU);

ALTER TABLE PROJECT_OWNER.CICLURI_INC_DESC ADD CONSTRAINT FK_CICLURI FOREIGN KEY (ID_MASURATOARE) REFERENCES PROJECT_OWNER.MASURATORI(ID_MASURATOARE);

CREATE OR REPLACE TRIGGER cicluri_insert_trigger
BEFORE INSERT ON PROJECT_OWNER.CICLURI_INC_DESC
FOR EACH ROW
BEGIN
  SELECT ciclu_id_seq.NEXTVAL INTO :new.ID_CICLU FROM dual;
END;

CREATE SEQUENCE incarcari_id_seq START WITH 1234 INCREMENT BY 1;


CREATE TABLE PROJECT_OWNER.INCARCARI(ID_INCARCARE,
ID_MASURATOARE,
CURENT_INCARCARE,
TENSIUNE_INCARCARE) AS
SELECT
	incarcari_id_seq.NEXTVAL,
	ID_MASURATOARE,
	CURENT_INCARCARE,
	TENSIUNE_INCARCARE
FROM
	PROJECT_OWNER.MASURATORI
WHERE
	1 = 2;
	
ALTER TABLE PROJECT_OWNER.INCARCARI ADD CONSTRAINT PK_INCARCARI PRIMARY KEY (ID_INCARCARE);

ALTER TABLE PROJECT_OWNER.INCARCARI ADD CONSTRAINT FK_INCARCARI FOREIGN KEY (ID_MASURATOARE) REFERENCES PROJECT_OWNER.MASURATORI(ID_MASURATOARE);

CREATE OR REPLACE TRIGGER incarcari_insert_trigger
BEFORE INSERT ON PROJECT_OWNER.INCARCARI
FOR EACH ROW
BEGIN
  SELECT incarcari_id_seq.NEXTVAL INTO :new.ID_INCARCARE FROM dual;
END;

CREATE SEQUENCE descarcari_id_seq START WITH 4321 INCREMENT BY 1;

CREATE TABLE PROJECT_OWNER.DESCARCARI (ID_DESCARCARE,
ID_MASURATOARE,
CURENT_DESCARCARE,
TENSIUNE_DESCARCARE) AS
SELECT
	descarcari_id_seq.NEXTVAL,
	ID_MASURATOARE,
	CURENT_DESCARCARE,
	TENSIUNE_DESCARCARE
FROM
	PROJECT_OWNER.MASURATORI
WHERE
	1 = 2;
	

ALTER TABLE PROJECT_OWNER.DESCARCARI ADD CONSTRAINT PK_DESCARCARI PRIMARY KEY (ID_DESCARCARE);

ALTER TABLE PROJECT_OWNER.DESCARCARI ADD CONSTRAINT FK_DESCARCARI FOREIGN KEY (ID_MASURATOARE) REFERENCES PROJECT_OWNER.MASURATORI(ID_MASURATOARE);

CREATE OR REPLACE TRIGGER descarcari_insert_trigger
BEFORE INSERT ON PROJECT_OWNER.DESCARCARI
FOR EACH ROW
BEGIN
  SELECT descarcari_id_seq.NEXTVAL INTO :new.ID_DESCARCARE FROM dual;
END;